[metadata]
name = expert-spork
version = 0.1.0

[options]
package_dir =
    = .
packages = find:
python_requires = >=3.11

[tool:pytest]
testpaths = tests
addopts = --tb=short -q

[coverage:run]
source = src
branch = True

[coverage:report]
show_missing = True
skip_covered = False
fail_under = 80
omit =
    src/__init__.py

[coverage:html]
directory = htmlcov
