"""add controlled to drugs

Revision ID: 5e91046640b3
Revises: 7529263baaae
Create Date: 2026-06-01 11:17:44.489521
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5e91046640b3'
down_revision: Union[str, None] = '7529263baaae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drugs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('controlled', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_drugs_controlled'), ['controlled'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drugs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drugs_controlled'))
        batch_op.drop_column('controlled')

    # ### end Alembic commands ###
