"""add deleted_at to users

Revision ID: 7529263baaae
Revises: 8e9e73084332
Create Date: 2026-06-01 10:47:52.057195
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7529263baaae'
down_revision: Union[str, None] = '8e9e73084332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
