"""add rx_source to drugs

Revision ID: 8e9e73084332
Revises: e39abce8920f
Create Date: 2026-06-01 10:09:03.767067
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8e9e73084332'
down_revision: Union[str, None] = 'e39abce8920f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drugs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rx_source', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drugs', schema=None) as batch_op:
        batch_op.drop_column('rx_source')

    # ### end Alembic commands ###
