"""initial schema

Revision ID: e39abce8920f
Revises: 
Create Date: 2026-05-31 16:34:32.507335
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e39abce8920f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=False),
    sa.Column('generic', sa.String(length=255), nullable=False),
    sa.Column('form', sa.String(length=64), nullable=False),
    sa.Column('strength', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=False),
    sa.Column('barcode', sa.String(length=32), nullable=False),
    sa.Column('price_egp', sa.Float(), nullable=False),
    sa.Column('rx', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drugs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drugs_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_drugs_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_drugs_generic'), ['generic'], unique=False)
        batch_op.create_index(batch_op.f('ix_drugs_name_ar'), ['name_ar'], unique=False)
        batch_op.create_index(batch_op.f('ix_drugs_name_en'), ['name_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_drugs_rx'), ['rx'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=128), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drug_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CART', 'PENDING_RX_VERIFICATION', 'PENDING_PAYMENT', 'PAID', 'FULFILLED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('requires_rx_verification', sa.Boolean(), nullable=False),
    sa.Column('rx_verified_by', sa.String(length=255), nullable=False),
    sa.Column('total_egp', sa.Float(), nullable=False),
    sa.Column('paymob_order_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_egp', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('orders')
    op.drop_table('inventory')
    op.drop_table('consents')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('drugs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drugs_rx'))
        batch_op.drop_index(batch_op.f('ix_drugs_name_en'))
        batch_op.drop_index(batch_op.f('ix_drugs_name_ar'))
        batch_op.drop_index(batch_op.f('ix_drugs_generic'))
        batch_op.drop_index(batch_op.f('ix_drugs_category'))
        batch_op.drop_index(batch_op.f('ix_drugs_barcode'))

    op.drop_table('drugs')
    # ### end Alembic commands ###
